export enum ActivityType {
  DEAL_CREATED = 'DEAL_CREATED',
  STAGE_CHANGED = 'STAGE_CHANGED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  NOTE_ADDED = 'NOTE_ADDED',
  CLIENT_CREATED = 'CLIENT_CREATED',
}
